id: I80E0AA90
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T19:29:41+00:00'
last_modified: '2022-06-09T04:35:27.428147+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5144
  title: མདོ་སྔགས་ཟུང་དུ་འཇུག་པའི་སྤྱོད་ཡུལ་ལམ་འཁྱེར་སངས་རྒྱས་ལམ་བཞུགས་སོགས་ཉེར་མཁོའི་སྐོར་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1918':
      image_group_id: I3CN5146
      title: Volume 1 of mdo sngags zung du 'jug pa'i spyod yul lam 'khyer sangs rgyas
        lam bzhugs sogs nyer mkho'i skor 'ga' phyogs gcig tu bsgrigs pa/
      total_pages: 52
      order: 1
      base_file: 1918.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
