id: P007074
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5144
  title: མདོ་སྔགས་ཟུང་དུ་འཇུག་པའི་སྤྱོད་ཡུལ་ལམ་འཁྱེར་སངས་རྒྱས་ལམ་བཞུགས་སོགས་ཉེར་མཁོའི་སྐོར་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  volumes:
    f7ca65fee7e24bf9b0e6c483a419f036:
      image_group_id: I3CN5146
      title: ''
      volume_number: 1
      total_pages: 52
ebook_metadata:
  title: མདོ་སྔགས་ཟུང་དུ་འཇུག་པའི་སྤྱོད་ཡུལ་ལམ་འཁྱེར་སངས་རྒྱས་ལམ་བཞུགས་སོགས་ཉེར་མཁོའི་སྐོར་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  sku: P007074
  cover: cover.jpg
  layers:
  - pagination
