id: P007074
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:39:52.702347
source_metadata:
  id: bdr:W3CN5144
  title: མདོ་སྔགས་ཟུང་དུ་འཇུག་པའི་སྤྱོད་ཡུལ་ལམ་འཁྱེར་སངས་རྒྱས་ལམ་བཞུགས་སོགས་ཉེར་མཁོའི་སྐོར་འགའ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  volumes:
    f1655f38017149ff88bf06fc2f7a7bc1:
      image_group_id: I3CN5146
      title: Volume 1 of mdo sngags zung du 'jug pa'i spyod yul lam 'khyer sangs rgyas
        lam bzhugs sogs nyer mkho'i skor 'ga' phyogs gcig tu bsgrigs pa/
      volume_number: 1
      total_pages: 52
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
